'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class admin_centres
    
    '''<summary>
    '''mvCentres control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mvCentres As Global.System.Web.UI.WebControls.MultiView
    
    '''<summary>
    '''vCentreList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vCentreList As Global.System.Web.UI.WebControls.View
    
    '''<summary>
    '''lbtAddCentre control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtAddCentre As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''dsCentresList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsCentresList As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''dsContractTypes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsContractTypes As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''CentresGridViewExporter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CentresGridViewExporter As Global.DevExpress.Web.ASPxGridViewExporter
    
    '''<summary>
    '''bsgvCentres control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bsgvCentres As Global.DevExpress.Web.Bootstrap.BootstrapGridView
    
    '''<summary>
    '''vCentreAddEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vCentreAddEdit As Global.System.Web.UI.WebControls.View
    
    '''<summary>
    '''hfCentreID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfCentreID As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''dsCentreDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsCentreDetails As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''dsRegions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsRegions As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''dsCentreTypes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsCentreTypes As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''fvCentreDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fvCentreDetails As Global.System.Web.UI.WebControls.FormView
    
    '''<summary>
    '''lblModalHeading control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblModalHeading As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblModalMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblModalMessage As Global.System.Web.UI.WebControls.Label
End Class
