'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class admin_landing

    '''<summary>
    '''bspcLandingTabs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bspcLandingTabs As Global.DevExpress.Web.Bootstrap.BootstrapPageControl

    '''<summary>
    '''dsOrganisations control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsOrganisations As Global.System.Web.UI.WebControls.ObjectDataSource

    '''<summary>
    '''dsBrands control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsBrands As Global.System.Web.UI.WebControls.ObjectDataSource

    '''<summary>
    '''bsgvBrands control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bsgvBrands As Global.DevExpress.Web.Bootstrap.BootstrapGridView

    '''<summary>
    '''bsppPreview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bsppPreview As Global.DevExpress.Web.Bootstrap.BootstrapPopupControl

    '''<summary>
    '''frmPreview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmPreview As Global.System.Web.UI.HtmlControls.HtmlIframe
End Class
