'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class admin_faqs
    
    '''<summary>
    '''dsFAQs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsFAQs As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''mvFAQ control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mvFAQ As Global.System.Web.UI.WebControls.MultiView
    
    '''<summary>
    '''vListFAQs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vListFAQs As Global.System.Web.UI.WebControls.View
    
    '''<summary>
    '''lbtAddFAQ control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtAddFAQ As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lbtClearFilters control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtClearFilters As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lbtDownloadFAQs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtDownloadFAQs As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''bsgvFAQs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bsgvFAQs As Global.DevExpress.Web.Bootstrap.BootstrapGridView
    
    '''<summary>
    '''FAQsGridViewExporter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FAQsGridViewExporter As Global.DevExpress.Web.ASPxGridViewExporter
    
    '''<summary>
    '''vAddEditFAQ control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vAddEditFAQ As Global.System.Web.UI.WebControls.View
    
    '''<summary>
    '''dsFAQInsertEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsFAQInsertEdit As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''lblFAQTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFAQTitle As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''fvFAQ control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fvFAQ As Global.System.Web.UI.WebControls.FormView
End Class
