'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class admin_resources
    
    '''<summary>
    '''mvResources control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mvResources As Global.System.Web.UI.WebControls.MultiView
    
    '''<summary>
    '''vResourcesList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vResourcesList As Global.System.Web.UI.WebControls.View
    
    '''<summary>
    '''lbtAddNewResource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtAddNewResource As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''dsResources control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsResources As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''DownloadsGridViewExporter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DownloadsGridViewExporter As Global.DevExpress.Web.ASPxGridViewExporter
    
    '''<summary>
    '''bsgvDownloads control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bsgvDownloads As Global.DevExpress.Web.Bootstrap.BootstrapGridView
    
    '''<summary>
    '''vAddEditResource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vAddEditResource As Global.System.Web.UI.WebControls.View
    
    '''<summary>
    '''dsAddEditResource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsAddEditResource As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''fvResource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fvResource As Global.System.Web.UI.WebControls.FormView
End Class
