'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class coursedelegates

    '''<summary>
    '''lblCourseSelect control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCourseSelect As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddCustomisationSelector control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddCustomisationSelector As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''cbActiveOnly control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbActiveOnly As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CustomisationsDataSourceCourse control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CustomisationsDataSourceCourse As Global.System.Web.UI.WebControls.ObjectDataSource

    '''<summary>
    '''dsDelegatesForCustomisation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsDelegatesForCustomisation As Global.System.Web.UI.WebControls.ObjectDataSource

    '''<summary>
    '''DelegateGridViewExporter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DelegateGridViewExporter As Global.DevExpress.Web.ASPxGridViewExporter

    '''<summary>
    '''bsgvDelegatesForCustomisation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bsgvDelegatesForCustomisation As Global.DevExpress.Web.Bootstrap.BootstrapGridView

    '''<summary>
    '''lblCFMHeading control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCFMHeading As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''hfCFProgressID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfCFProgressID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''pnlField1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlField1 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblCustField1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCustField1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tbField1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbField1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddField1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddField1 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''pnlField2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlField2 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblCustField2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCustField2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tbField2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbField2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddField2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddField2 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''pnlField3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlField3 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblCustField3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCustField3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tbField3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbField3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddField3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddField3 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lbtSaveCustFields control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtSaveCustFields As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''DelegatesModals control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DelegatesModals As Global.ITSP_TrackingSystemRefactor.DelegatesModals
End Class
