'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class SiteMaster

    '''<summary>
    '''pnlMainLogo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlMainLogo As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''logoImage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents logoImage As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''nhsdlogo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents nhsdlogo As Global.System.Web.UI.HtmlControls.HtmlImage

    '''<summary>
    '''liCentre control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents liCentre As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''liCentreLogins control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents liCentreLogins As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''liReportFWA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents liReportFWA As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''liDCSReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents liDCSReport As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lbtDownloadDCSReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtDownloadDCSReport As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''liDelegates control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents liDelegates As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''liCourseSetup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents liCourseSetup As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''liSupervisor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents liSupervisor As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''liSupport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents liSupport As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''liTickets control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents liTickets As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''liAdmin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents liAdmin As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''liAdminConfiguration control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents liAdminConfiguration As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''liPrelogin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents liPrelogin As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''liAdminadminusers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents liAdminadminusers As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''liAdmincentres control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents liAdmincentres As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''liAdmincentrecourses control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents liAdmincentrecourses As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''liAdmindelegates control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents liAdmindelegates As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''liAdminresources control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents liAdminresources As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''liAdminfaqs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents liAdminfaqs As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''liAdminNotifications control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents liAdminNotifications As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''usermx control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents usermx As Global.ITSP_TrackingSystemRefactor.usermx

    '''<summary>
    '''hlHelpBtn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlHelpBtn As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''breadtray control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents breadtray As Global.System.Web.UI.WebControls.ContentPlaceHolder

    '''<summary>
    '''MainContent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MainContent As Global.System.Web.UI.WebControls.ContentPlaceHolder

    '''<summary>
    '''usermxmodals control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents usermxmodals As Global.ITSP_TrackingSystemRefactor.usermxmodals

    '''<summary>
    '''sch1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sch1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''liCentreLogins2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents liCentreLogins2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''sch2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sch2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''sch3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sch3 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''sch6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sch6 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''sch4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sch4 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''hlHelp2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlHelp2 As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''liTickets1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents liTickets1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''sch5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sch5 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''li2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents li2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lbltermsHeading control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbltermsHeading As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''litTOUDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litTOUDetail As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''Label8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label8 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''litPrivacy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litPrivacy As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''Label9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label9 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''litAccess control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litAccess As Global.System.Web.UI.WebControls.Literal
End Class
