'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class welcome
    
    '''<summary>
    '''lblCentreCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCentreCount As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblLearnerCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLearnerCount As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblLearningHours control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLearningHours As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblCompletionsCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCompletionsCount As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''brands control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents brands As Global.ITSP_TrackingSystemRefactor.brands
    
    '''<summary>
    '''products1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents products1 As Global.ITSP_TrackingSystemRefactor.products
    
    '''<summary>
    '''cstories control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cstories As Global.ITSP_TrackingSystemRefactor.cstories
    
    '''<summary>
    '''quotes1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents quotes1 As Global.ITSP_TrackingSystemRefactor.quotes
    
    '''<summary>
    '''newstimeline control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents newstimeline As Global.ITSP_TrackingSystemRefactor.newstimeline
End Class
