'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ReminderForm
    
    '''<summary>
    '''lblAppointmentSubject control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAppointmentSubject As Global.DevExpress.Web.ASPxLabel
    
    '''<summary>
    '''lblStartTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStartTime As Global.DevExpress.Web.ASPxLabel
    
    '''<summary>
    '''lblAppointmentStartTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAppointmentStartTime As Global.DevExpress.Web.ASPxLabel
    
    '''<summary>
    '''lbItems control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbItems As Global.DevExpress.Web.ASPxListBox
    
    '''<summary>
    '''btnDismissAll control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDismissAll As Global.DevExpress.Web.ASPxButton
    
    '''<summary>
    '''btnOpenItem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnOpenItem As Global.DevExpress.Web.ASPxButton
    
    '''<summary>
    '''btnDismiss control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDismiss As Global.DevExpress.Web.ASPxButton
    
    '''<summary>
    '''lblClickSnooze control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblClickSnooze As Global.DevExpress.Web.ASPxLabel
    
    '''<summary>
    '''cbSnooze control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbSnooze As Global.DevExpress.Web.ASPxComboBox
    
    '''<summary>
    '''btnSnooze control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSnooze As Global.DevExpress.Web.ASPxButton
End Class
