'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class brand

    '''<summary>
    '''dsAppsForBrand control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsAppsForBrand As Global.System.Web.UI.WebControls.ObjectDataSource

    '''<summary>
    '''dsBrandCategories control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsBrandCategories As Global.System.Web.UI.WebControls.ObjectDataSource

    '''<summary>
    '''dsBrandTopics control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsBrandTopics As Global.System.Web.UI.WebControls.ObjectDataSource

    '''<summary>
    '''bimgBrand control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bimgBrand As Global.DevExpress.Web.ASPxBinaryImage

    '''<summary>
    '''lblBrandName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBrandName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblBrandDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBrandDescription As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''dsBrandTutorials control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsBrandTutorials As Global.System.Web.UI.WebControls.ObjectDataSource

    '''<summary>
    '''pnlBrandTutorials control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlBrandTutorials As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''rptBrandTutorials control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptBrandTutorials As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''pnlTabs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlTabs As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''rptBrandCategories control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptBrandCategories As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''rptBrandTopics control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptBrandTopics As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''SortSelect control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SortSelect As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''rptBrandApps control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptBrandApps As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''itspbenefits control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents itspbenefits As Global.ITSP_TrackingSystemRefactor.itspbenefits

    '''<summary>
    '''rptModals control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptModals As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''Label6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label6 As Global.System.Web.UI.WebControls.Label
End Class
