'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class itspbenefits
    
    '''<summary>
    '''upCalculator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upCalculator As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''pnlCalculator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlCalculator As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblCalcTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCalcTitle As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblOrgSize control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOrgSize As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tbOrgSize control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbOrgSize As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblPercentEntry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPercentEntry As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tbPercentEntry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbPercentEntry As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblPercentL1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPercentL1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tbPercentL1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbPercentL1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblAvPayband control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAvPayband As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddAvgPayband control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddAvgPayband As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''btnCalculate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCalculate As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lblCalcOutput control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCalcOutput As Global.System.Web.UI.WebControls.Label
End Class
