'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class product
    
    '''<summary>
    '''dsProducts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsProducts As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''dsFeatures control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsFeatures As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''rptProducts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptProducts As Global.System.Web.UI.WebControls.Repeater
    
    '''<summary>
    '''rptFeatures control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptFeatures As Global.System.Web.UI.WebControls.Repeater
    
    '''<summary>
    '''quotes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents quotes As Global.ITSP_TrackingSystemRefactor.quotes
    
    '''<summary>
    '''newstimeline control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents newstimeline As Global.ITSP_TrackingSystemRefactor.newstimeline
End Class
