'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ContentCreator
    
    '''<summary>
    '''lblLicenceStart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLicenceStart As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblLicenceCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLicenceCode As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''hlDownloadCC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlDownloadCC As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''lblCCVersion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCCVersion As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''litReleaseNotes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litReleaseNotes As Global.System.Web.UI.WebControls.Literal
End Class
